[env]
TERM = "xterm-256color"

[window]
padding = { x = 0, y = 5 }
dynamic_padding = true
decorations = "None"
opacity = 0.825
blur = true
option_as_alt = "OnlyLeft"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { style = "Regular" }
italic = { style = "Regular" }
bold_italic = { style = "Regular" }
offset = { x = 1, y = 1 }
size = 14
# size= 13

[colors]
cursor = { text = "#e8e8e8", background = "#8a94a9" }
selection = { text = "#abb2bf", background = "#323844" }

[colors.primary]
foreground = "#abb2bf"
background = "#051431"

[colors.normal]
black = "#131d2c"
red = "#e5646e"
green = "#89d354"
yellow = "#e4b763"
blue = "#2677c9"
magenta = "#c678dd"
cyan = "#32d4e8"
white = "#abb2bf"

[colors.bright]
black = "#3a445a"
red = "#e5646e"
green = "#8ac16f"
yellow = "#e4b763"
blue = "#38a3e9"
magenta = "#c678dd"
cyan = "#32d4e8"
white = "#abb2bf"

[cursor]
style = { shape = "Block", blinking = "Always" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [{ key = "Key6", mods = "Control", chars = "\u001e" }]
