vim.keymap.set("n", "<leader>bd", [[<CMD>bd<CR>]])
vim.keymap.set("n", "<leader>oo", [[<CMD>only<CR>]])
vim.keymap.set("n", "<leader>b[[", [[<CMD>BufferLineCloseLeft<CR>]])
vim.keymap.set("n", "<leader>b]]", [[<CMD>BufferLineCloseRight<CR>]])
vim.keymap.set("n", "<leader>be", [[<CMD>BufferLineSortByExtension<CR>]])
vim.keymap.set("n", "<leader>bf", [[<CMD>BufferLineSortByDirectory<CR>]])
vim.keymap.set("n", "<leader>bn", [[<CMD>BufferLineCycleNext<CR>]])
vim.keymap.set("n", "<leader>bp", [[<CMD>BufferLineCyclePrev<CR>]])
vim.keymap.set("n", "<leader>bh", [[<CMD>split<CR>]])
vim.keymap.set("n", "<leader>bv", [[<CMD>vsplit<CR>]])
vim.keymap.set("n", "<leader>ws[", [[<CMD>vertical resize -5<CR>]])
vim.keymap.set("n", "<leader>ws]", [[<CMD>vertical resize +5<CR>]])
vim.keymap.set("n", "<leader>ws;", [[<CMD>resize -5<CR>]])
vim.keymap.set("n", "<leader>ws'", [[<CMD>resize +5<CR>]])
